import { useEffect, useState } from "react";
import { Check, Clock, Package, Truck, X } from "lucide-react";
import { getOrders, type Order } from "../../services/api";

const statusSteps = ["Recebido", "Em preparacao", "Pronto", "Saiu para entrega", "Entregue"];
const statusLabels: Record<string, string> = { Recebido: "Recebido", "Em preparacao": "Em preparação", Pronto: "Pronto", "Saiu para entrega": "Saiu para entrega", Entregue: "Finalizado", Cancelado: "Cancelado" };
const icons: Record<string, any> = { Recebido: Clock, "Em preparacao": Package, Pronto: Check, "Saiu para entrega": Truck, Entregue: Check, Cancelado: X };
const colors: Record<string, string> = { Recebido: "bg-blue-50 text-blue-600", "Em preparacao": "bg-amber-50 text-amber-600", Pronto: "bg-violet-50 text-violet-600", "Saiu para entrega": "bg-sky-50 text-sky-600", Entregue: "bg-[#dcfce7] text-[#15803d]", Cancelado: "bg-red-50 text-red-600" };
function formatDate(value: string) { return new Date(value).toLocaleDateString("pt-BR"); }

export default function Pedidos() {
  const [orders, setOrders] = useState<Order[]>([]);
  useEffect(() => { getOrders().then((result) => setOrders(result.data)).catch(() => setOrders([])); }, []);
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold text-[#111827]">Meus Pedidos</h1><p className="text-sm text-[#6b7280]">{orders.length} pedidos realizados</p></div><div className="space-y-3">{orders.map((order) => { const Icon = icons[order.status] || Package; const color = colors[order.status] || "bg-gray-100 text-gray-500"; const current = statusSteps.indexOf(order.status); return <div key={order.id} className="bg-white rounded-2xl border border-[#e5e7eb] shadow-sm p-5"><div className="flex items-start gap-4"><div className={`p-3 rounded-xl flex-shrink-0 ${color}`}><Icon size={20} /></div><div className="flex-1 min-w-0"><div className="flex items-center justify-between gap-2"><span className="font-bold text-[#111827] font-mono text-sm">#{order.id}</span><span className={`text-xs px-2.5 py-1 rounded-full font-medium ${color}`}>{statusLabels[order.status] || order.status}</span></div><p className="text-sm text-[#374151] mt-1">{order.products || "Itens do pedido"}</p><div className="flex items-center justify-between mt-2"><span className="text-xs text-[#9ca3af]">{formatDate(order.created_at)}</span><span className="font-bold text-[#111827]">R$ {Number(order.total).toFixed(2)}</span></div></div></div>{current >= 0 && current < statusSteps.length - 1 && <div className="mt-4 pt-4 border-t border-[#f3f4f6]"><div className="flex items-center gap-1">{statusSteps.map((step, index) => <div key={step} className="flex items-center flex-1 last:flex-none"><div className={`w-3 h-3 rounded-full ${index <= current ? "bg-[#16a34a]" : "bg-[#e5e7eb]"}`} />{index < statusSteps.length - 1 && <div className={`flex-1 h-px ${index < current ? "bg-[#16a34a]" : "bg-[#e5e7eb]"}`} />}</div>)}</div><p className="text-xs text-[#16a34a] font-medium mt-1.5">{statusLabels[order.status] || order.status}</p></div>}</div>; })}{!orders.length && <div className="bg-white rounded-2xl border border-dashed border-[#d1d5db] p-10 text-center text-sm text-[#6b7280]">Você ainda não possui pedidos.</div>}</div></div>;
}
